//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoNatal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey
    {
        public int id { get; set; }
        public int health_worker_id { get; set; }
        public int client_id { get; set; }
        public string question_1 { get; set; }
        public string quesiton_2 { get; set; }
        public string question_3 { get; set; }
        public string question_4 { get; set; }
        public string question_5 { get; set; }
        public string question_6 { get; set; }
        public string question_7 { get; set; }
        public string question_8 { get; set; }
        public string question_9 { get; set; }
        public string question_10 { get; set; }
        public string question_11 { get; set; }
        public string question_12 { get; set; }
        public string question_13 { get; set; }
        public string question_14 { get; set; }
        public string question_15 { get; set; }
        public string question_16 { get; set; }
        public string question_17 { get; set; }
        public string question_18 { get; set; }
        public string question_19 { get; set; }
        public string question_20 { get; set; }
        public string quesiton_21 { get; set; }
        public string question_22 { get; set; }
        public string quesiton_23 { get; set; }
        public string question_24 { get; set; }
        public string question_25 { get; set; }
    
        public virtual client client { get; set; }
        public virtual health_worker health_worker { get; set; }
    }
}
